$axure.loadCurrentPage({
  "url":"skeleton_e-commerce_interface.html",
  "generationDate":new Date(1399905695302.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"ShoppingBagCounter",
"ProductColor",
"ShippingFirstName",
"ShippingLastName",
"ShippingStreet",
"ShippingCity",
"ShippingState",
"ShippingZip"],
  "page":{
    "packageId":"45ca573d4c764f5293e39d4d5d93830f",
    "type":"Axure:Page",
    "name":"Skeleton E-Commerce Interface",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1848528b6aa4e3f9121fe65eaa354cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'ArialMT', 'Arial'",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"20px",
            "paddingTop":"20",
            "paddingBottom":"20",
            "location":{
              "x":10,
              "y":100},
            "size":{
              "width":720,
              "height":280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b845d495ed41dbbc788cfc58646cb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ArialMT', 'Arial'",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"20px",
                "paddingTop":"20",
                "paddingBottom":"20",
                "location":{
                  "x":10,
                  "y":100},
                "size":{
                  "width":720,
                  "height":280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/skeleton_e-commerce_interface/u0.png"}},
{
          "id":"ba6e9e7088024d868bffb1ec99ee7b09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'ArialMT', 'Arial'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":210,
              "y":260},
            "size":{
              "width":200,
              "height":100},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8d3e5f021334179b3cd1fc13976da97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ArialMT', 'Arial'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":210,
                  "y":260},
                "size":{
                  "width":200,
                  "height":100},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a26306bf97f44e3690449e64b4af33da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'ArialMT', 'Arial'",
            "fontSize":"12px",
            "verticalAlignment":"top",
            "lineSpacing":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":470,
              "y":180},
            "size":{
              "width":230,
              "height":110},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81edc3b241054762b82046347d22a6e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ArialMT', 'Arial'",
                "fontSize":"12px",
                "verticalAlignment":"top",
                "lineSpacing":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":470,
                  "y":180},
                "size":{
                  "width":230,
                  "height":110},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/skeleton_e-commerce_interface/u4.png"}},
{
          "id":"2d84162a6cfc4196a99ab12d769d4b96",
          "label":"Hint",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":238},
            "size":{
              "width":52,
              "height":42}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"53b4fb7e96ce41fcbf8408a1cc98fca4",
              "label":"Message",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0f32d1c2afbc498fb9d6f087157f1f15",
                  "label":"",
                  "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "paddingTop":"5",
                    "paddingBottom":"5",
                    "location":{
                      "x":2,
                      "y":2},
                    "size":{
                      "width":50,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2dc0d660132143c3921c561b80cbb0b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "paddingTop":"5",
                        "paddingBottom":"5",
                        "location":{
                          "x":2,
                          "y":2},
                        "size":{
                          "width":50,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/skeleton_e-commerce_interface/u7.png"}},
{
                  "id":"56330825bb9b4dbba86f46dacfe3f32f",
                  "label":"",
                  "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":17,
                      "y":32},
                    "size":{
                      "width":20,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1440ea3e90946e1bf8bfe8e07c20f7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":17,
                          "y":32},
                        "size":{
                          "width":20,
                          "height":10},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/skeleton_e-commerce_interface/u9.png"}},
{
                  "id":"e24eea631ef7406aa217c226d2071776",
                  "label":"",
                  "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Helvetica', 'Helvetica'",
                    "fontSize":"11px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "paddingTop":"0",
                    "paddingBottom":"0",
                    "size":{
                      "width":50,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45885a99f0a74f9f87ba374971e6b740",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Helvetica', 'Helvetica'",
                        "fontSize":"11px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "paddingTop":"0",
                        "paddingBottom":"0",
                        "size":{
                          "width":50,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/skeleton_e-commerce_interface/u11.png"}},
{
                  "id":"3423ed3eff3947c298f5633d93dedb15",
                  "label":"",
                  "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'', '', 'Franklin Gothic Book'",
                    "fontSize":"11px",
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "location":{
                      "x":15,
                      "y":30},
                    "size":{
                      "width":20,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0fa57d02217471d9637c0d9cebad91c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d84162a6cfc4196a99ab12d769d4b96",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'', '', 'Franklin Gothic Book'",
                        "fontSize":"11px",
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "location":{
                          "x":15,
                          "y":30},
                        "size":{
                          "width":20,
                          "height":10},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/skeleton_e-commerce_interface/u13.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9f8b335a54c24699b8e07a4d3402ba57",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":170},
            "size":{
              "width":10,
              "height":190},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/skeleton_e-commerce_interface/u15_line.png"}},
{
          "id":"6c5261ff8a9642f0b9d3cda8395a54c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
}},
            "location":{
              "x":472,
              "y":302},
            "size":{
              "width":224,
              "height":65},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca92df3b27164d5a9a6e91e9496bc7fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
}},
                "location":{
                  "x":472,
                  "y":302},
                "size":{
                  "width":224,
                  "height":65},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/skeleton_e-commerce_interface/u16.png",
            "mouseOver~":"images/skeleton_e-commerce_interface/u16_mouseOver.png",
            "mouseDown~":"images/skeleton_e-commerce_interface/u16_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a1848528b6aa4e3f9121fe65eaa354cd":{
      "scriptId":"u0"},
    "42b845d495ed41dbbc788cfc58646cb8":{
      "scriptId":"u1"},
    "ba6e9e7088024d868bffb1ec99ee7b09":{
      "scriptId":"u2"},
    "a8d3e5f021334179b3cd1fc13976da97":{
      "scriptId":"u3"},
    "a26306bf97f44e3690449e64b4af33da":{
      "scriptId":"u4"},
    "81edc3b241054762b82046347d22a6e2":{
      "scriptId":"u5"},
    "2d84162a6cfc4196a99ab12d769d4b96":{
      "scriptId":"u6"},
    "0f32d1c2afbc498fb9d6f087157f1f15":{
      "scriptId":"u7"},
    "2dc0d660132143c3921c561b80cbb0b9":{
      "scriptId":"u8"},
    "56330825bb9b4dbba86f46dacfe3f32f":{
      "scriptId":"u9"},
    "f1440ea3e90946e1bf8bfe8e07c20f7a":{
      "scriptId":"u10"},
    "e24eea631ef7406aa217c226d2071776":{
      "scriptId":"u11"},
    "45885a99f0a74f9f87ba374971e6b740":{
      "scriptId":"u12"},
    "3423ed3eff3947c298f5633d93dedb15":{
      "scriptId":"u13"},
    "a0fa57d02217471d9637c0d9cebad91c":{
      "scriptId":"u14"},
    "9f8b335a54c24699b8e07a4d3402ba57":{
      "scriptId":"u15"},
    "6c5261ff8a9642f0b9d3cda8395a54c1":{
      "scriptId":"u16"},
    "ca92df3b27164d5a9a6e91e9496bc7fc":{
      "scriptId":"u17"}}});